### ISSUE TITLE
List Index Out Of Range

### ISSUE THREAD

**Issue by Rishan123** [Rishan123/Science-Fair-2019#1]
When I run the program, I get an error along the lines of, 
`USAGE: facerec_demo.py </home/pi/Face Detection/rs> [/home/pi/Face Detection/rs/live]
Traceback (most recent call last):
  File "/home/pi/Face Detection/face_recognize.py", line 87, in <module>
    face_rec()
  File "/home/pi/Face Detection/face_recognize.py", line 62, in face_rec
    [X,y] = read_images(sys.argv[1])
IndexError: list index out of range`
 Research being done about the problem

**Comment by Rishan123** [comment]
I've solved the problem: You need to run the program in the terminal with the arguments in the USAGE print.

**Comment by Rishan123** [comment]
But I get another problem:

`Traceback (most recent call last):
  File "face_demo.py", line 88, in <module>
    face_rec()                           
  File "face_demo.py", line 67, in face_rec
    model = cv2.face.createEigenFaceRecognizer()
AttributeError: module 'cv2.face' has no attribute 'createEigenFaceRecognizer'
`
Can anybody help?

**Comment by Rishan123** [comment]
Fixed as well.
Instead of writing `createEigenFaceRecognizer`, you need to write `EigenFaceRecognizer_create()`
